#! /bin/bash -e
brad_home_page="http://www.seanet.com/~bradbell/home.htm"
if [ -e doc ]
then
	rm -r doc
fi
mkdir doc
cd doc
if ! omhelp ../mat2cpp.omh -xml -noframe -debug -image_link "$brad_home_page"
then
	echo "aborting (see OMhelp error message above)"
	exit
fi
omhelp ../mat2cpp.omh -noframe -debug -image_link "$brad_home_page"
